version: 2
references:
# ----------------------------
# Cache Configuration
# ----------------------------
  cache_key: &cache_key
    key: cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle
        - ~/.m2
# ----------------------------
# Docker Configuration
# ----------------------------
android_config: &android_config
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      ANDROID_SDK_VERSION: 27
      ANDROID_BUILD_TOOLS_VERSION: 27.0.2
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2560M -XX:+HeapDumpOnOutOfMemoryError"'

# ----------------------------
# Job Section
# ----------------------------

jobs:

  build:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Install AWS CLI
          command:
            sudo apt-get -y -qq install awscli
      - run:
          name: Fetch signing data
          command: |
            aws configure set s3.signature_version s3v4
            aws s3 cp s3://idee-android/debug.jks app/debug.jks
            aws s3 cp s3://idee-android/release.jks app/release.jks
            aws s3 cp s3://idee-android/keystore.properties app/keystore.properties
      - run:
          name: Clean
          command: ./gradlew clean
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - *save_cache
      - run:
          name: Debug unit tests
          command: ./gradlew testDebug
      - run:
          name: Release unit tests
          command: ./gradlew testRelease
      - run:
          name: Build Release
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/
      - store_artifacts:
          path: app/build/outputs/mapping/
      - store_test_results:
          path: app/build/test-results/
